import { Link } from "wouter";
import { useListOutputs, getListOutputsQueryKey } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Files, RefreshCw, Eye, FileCode2, Clock, HardDrive,
  Download, Package, FolderOpen,
} from "lucide-react";

function formatBytes(bytes: number) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
}

const PAGE_TYPE_COLORS: Record<string, string> = {
  login:     "bg-blue-500/15 text-blue-400 border-blue-500/30",
  dashboard: "bg-purple-500/15 text-purple-400 border-purple-500/30",
  index:     "bg-green-500/15 text-green-400 border-green-500/30",
  register:  "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
  form:      "bg-orange-500/15 text-orange-400 border-orange-500/30",
};

export default function Outputs() {
  const queryClient = useQueryClient();
  const { data, isLoading, isError } = useListOutputs({
    query: { queryKey: getListOutputsQueryKey() },
  });

  const outputs = data?.outputs ?? [];

  return (
    <div className="max-w-5xl mx-auto">
      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight mb-2 flex items-center gap-3">
            <Files className="w-7 h-7 text-primary" />
            Generated Projects
          </h1>
          <p className="text-muted-foreground text-sm">
            All multi-file projects generated by the agent. Preview or download the full project ZIP.
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="gap-2 border-border"
          onClick={() => queryClient.invalidateQueries({ queryKey: getListOutputsQueryKey() })}
        >
          <RefreshCw className="w-4 h-4" />
          Refresh
        </Button>
      </div>

      {isLoading && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {[...Array(4)].map((_, i) => (
            <Card key={i} className="bg-card border-border">
              <CardContent className="p-5">
                <div className="h-5 w-32 bg-muted rounded animate-pulse mb-3" />
                <div className="h-4 w-48 bg-muted/60 rounded animate-pulse mb-2" />
                <div className="h-4 w-24 bg-muted/40 rounded animate-pulse" />
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {isError && (
        <Card className="border-destructive/40 bg-destructive/5">
          <CardContent className="p-8 text-center">
            <p className="text-destructive font-medium">Failed to load outputs.</p>
          </CardContent>
        </Card>
      )}

      {!isLoading && !isError && outputs.length === 0 && (
        <Card className="border-dashed border-border bg-card/50">
          <CardContent className="p-16 text-center">
            <FolderOpen className="w-12 h-12 text-muted-foreground/40 mx-auto mb-4" />
            <h3 className="text-lg font-semibold mb-2">No projects yet</h3>
            <p className="text-muted-foreground text-sm mb-6">
              Run a command from the Agent Console to generate your first project.
            </p>
            <Link href="/">
              <Button className="gap-2">Go to Console</Button>
            </Link>
          </CardContent>
        </Card>
      )}

      {!isLoading && !isError && outputs.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {outputs.map((file) => {
            const colorClass = PAGE_TYPE_COLORS[file.pageType] ?? "bg-primary/15 text-primary border-primary/30";
            const hasProject = !!file.projectSlug;

            return (
              <Card
                key={file.filename}
                className="bg-card border-border hover:border-primary/40 transition-all group"
              >
                <CardContent className="p-5">
                  {/* Header */}
                  <div className="flex items-start justify-between mb-3">
                    <div className="flex items-center gap-2 min-w-0">
                      {hasProject
                        ? <Package className="w-5 h-5 text-primary shrink-0" />
                        : <FileCode2 className="w-5 h-5 text-primary shrink-0" />}
                      <span className="font-mono text-sm font-semibold truncate">
                        {file.filename}
                      </span>
                    </div>
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded border capitalize shrink-0 ml-2 ${colorClass}`}>
                      {file.pageType}
                    </span>
                  </div>

                  {/* Project badge */}
                  {hasProject && (
                    <div className="mb-3 flex items-center gap-1.5 text-xs text-emerald-400">
                      <Package className="w-3 h-3" />
                      <span className="font-medium">Multi-file project ready</span>
                    </div>
                  )}

                  {/* Meta */}
                  <div className="flex items-center gap-4 text-xs text-muted-foreground mb-4 font-mono">
                    <span className="flex items-center gap-1.5">
                      <Clock className="w-3 h-3" />
                      {formatDate(file.createdAt)}
                    </span>
                    <span className="flex items-center gap-1.5">
                      <HardDrive className="w-3 h-3" />
                      {formatBytes(file.size)}
                    </span>
                  </div>

                  {/* Actions */}
                  <div className="flex gap-2">
                    <Link href={`/preview?file=${file.filename}`} className="flex-1">
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-full gap-2 border-border group-hover:border-primary/40 hover:text-primary transition-all"
                      >
                        <Eye className="w-4 h-4" />
                        Preview
                      </Button>
                    </Link>

                    {file.downloadUrl && (
                      <a href={file.downloadUrl} download className="flex-1">
                        <Button
                          size="sm"
                          className="w-full gap-2 bg-primary hover:bg-primary/90 text-primary-foreground"
                        >
                          <Download className="w-4 h-4" />
                          Download ZIP
                        </Button>
                      </a>
                    )}
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
